Alib: Alib::AObject Class Reference
Alib::AObject Class Reference abstract
#include <AObject.h>
Public Member Functions
AObject () noexcept
virtual ~AObject ()=default
AObject (const AObject &other)
AObject (AObject &&other) noexcept
AObject & operator= (const AObject &other)
AObject & operator= (AObject &&other) noexcept
virtual std::unique_ptr< AObject > clone () const =0
virtual std::size_t hash () const
const std::string & Oid () const noexcept
virtual std::string getClassName () const
bool valid () const noexcept
void setValid (bool valid) noexcept
void validate () noexcept
void invalidate () noexcept
AErrors getError () const noexcept
const char * errorName () const noexcept
void setError (AErrors err) noexcept
void resetError () noexcept
bool operator== (const AObject &other) const noexcept
bool operator!= (const AObject &other) const noexcept
virtual std::ostream & toStream (std::ostream &os) const
virtual std::istream & fromStream (std::istream &is)
virtual bool write (const std::string &fileName) const
virtual bool read (const std::string &fileName)
virtual std::ostream & printDescription (std::ostream &os) const
Protected Member Functions
virtual void m_copy (const AObject &other)
virtual void m_move (AObject &&other) noexcept
virtual bool m_compare (const AObject &other) const noexcept
virtual bool m_isValid () const noexcept
virtual std::ostream & m_printDescription (std::ostream &os) const
virtual std::ostream & m_printStatus (std::ostream &os) const
virtual std::ostream & m_print (std::ostream &os) const
virtual std::istream & m_parse (std::istream &is)
virtual bool m_write (std::ostream &os) const
virtual bool m_read (std::istream &is)
virtual std::ostream & m_toStream (std::ostream &os) const
virtual std::istream & m_fromStream (std::istream &is)
Static Protected Member Functions
static std::string generateOID ()
Protected Attributes
uint32_t p_magic {AOBJ_MAGIC}
uint32_t p_version {AOBJ_VERSION}
std::string p_oid
bool p_valid {true}
AErrors p_error {AErrors::noError}
Friends
std::ostream & operator<< (std::ostream &os, const AObject &obj)
std::istream & operator>> (std::istream &is, AObject &obj)
Detailed Description
Constructor & Destructor Documentation
AObject() [1/3]
Alib::AObject::AObject () inline noexcept
: p_oid(generateOID()) {}
~AObject()
virtual Alib::AObject::~AObject () virtual default
AObject() [2/3]
Alib::AObject::AObject (const AObject & other) inline
{ m_copy(other); }
References m_copy().
AObject() [3/3]
Alib::AObject::AObject (AObject && other) inline noexcept
{ m_move(std::move(other)); }
References m_move().
Member Function Documentation
clone()
virtual std::unique_ptr< AObject > Alib::AObject::clone () const nodiscard pure virtual
Implemented in Alib::AArray< T >.
errorName()
const char * Alib::AObject::errorName () const inline nodiscard noexcept
{ return ::Alib::getErrorName(p_error); }
References Alib::getErrorName(), and p_error.
Referenced by m_printStatus().
fromStream()
virtual std::istream & Alib::AObject::fromStream (std::istream & is) inline virtual
{ return m_fromStream(is); }
generateOID()
std::string Alib::AObject::generateOID () inline static protected
{
        static thread_local std::mt19937_64 rng(
            std::chrono::high_resolution_clock::now().time_since_epoch().count()
        );
        std::uniform_int_distribution<uint64_t> dist(0, 9999999999ULL);
        std::ostringstream oss;
        for(int i = 0; i < 3; ++i) {
            oss << std::setw(10) << std::setfill('0') << dist(rng);
            if(i != 2) oss << ".";
        }
        return oss.str();
    }
getClassName()
virtual std::string Alib::AObject::getClassName () const inline virtual
{ return "AObject"; }
getError()
AErrors Alib::AObject::getError () const inline nodiscard noexcept
{ return p_error; }
References p_error.
hash()
virtual std::size_t Alib::AObject::hash () const inline nodiscard virtual
Reimplemented in Alib::AArray< T >.
{ return std::hash<std::string>{}(p_oid); }
invalidate()
void Alib::AObject::invalidate () inline noexcept
{ p_valid = false; }
References p_valid.
m_compare()
virtual bool Alib::AObject::m_compare (const AObject & other) const inline nodiscard protected virtual noexcept
{
        return p_oid == other.p_oid;
    }
Referenced by operator==().
m_copy()
virtual void Alib::AObject::m_copy (const AObject & other) inline protected virtual
{
        p_oid = other.p_oid;
        p_valid = other.p_valid;
        p_error = other.p_error;
    }
References p_error, and p_valid.
Referenced by AObject(), Alib::AArray< T >::m_copy(), and operator=().
m_fromStream()
virtual std::istream & Alib::AObject::m_fromStream (std::istream & is) inline protected virtual
{ return m_parse(is); }
m_isValid()
virtual bool Alib::AObject::m_isValid () const inline nodiscard protected virtual noexcept
{ return p_valid; }
References p_valid.
m_move()
virtual void Alib::AObject::m_move (AObject && other) inline protected virtual noexcept
{
        p_oid = std::move(other.p_oid);
        p_valid = other.p_valid;
        p_error = other.p_error;
    }
References p_error, and p_valid.
Referenced by AObject(), Alib::AArray< T >::m_move(), and operator=().
m_parse()
virtual std::istream & Alib::AObject::m_parse (std::istream & is) inline protected virtual
{
        std::string oid;
        bool valid = false;
        int errInt = 0;
        uint32_t version = 0;
        is >> version >> oid >> valid >> errInt;
        if (is.good()) {
            p_version = version;
            p_oid = std::move(oid);
            p_valid = valid;
            p_error = static_cast<AErrors>(errInt);
        }
        return is;
    }
References p_error, and p_valid.
m_print()
virtual std::ostream & Alib::AObject::m_print (std::ostream & os) const inline protected virtual
{
        os << p_version << std::endl << p_oid << std::endl << p_valid << std::endl << static_cast<int>(p_error);
        return os;
    }
m_printDescription()
virtual std::ostream & Alib::AObject::m_printDescription (std::ostream & os) const inline protected virtual
{
        os << getClassName() << " [OID=" << p_oid << "]" << std::endl;
        return m_printStatus(os);
    }
m_printStatus()
virtual std::ostream & Alib::AObject::m_printStatus (std::ostream & os) const inline protected virtual
{
        os << "Valid=" << p_valid << " Error=" << errorName();
        return os;
    }
References errorName(), and p_valid.
m_read()
virtual bool Alib::AObject::m_read (std::istream & is) inline nodiscard protected virtual
{
        uint32_t magic = 0;
        is.read(reinterpret_cast<char*>(&magic), sizeof(magic));
        if (magic != AOBJ_MAGIC) return false;
        uint32_t version = 0;
        is.read(reinterpret_cast<char*>(&version), sizeof(version));
        if (!is.good()) return false;
        p_version = version;
        uint32_t oidLen = 0;
        is.read(reinterpret_cast<char*>(&oidLen), sizeof(oidLen));
        if (!is.good()) return false;
        std::string oid; oid.resize(oidLen);
        if (oidLen > 0) {
            is.read(oid.data(), oidLen);
            if (!is.good()) return false;
        }
        uint8_t validByte = 0;
        is.read(reinterpret_cast<char*>(&validByte), sizeof(validByte));
        if (!is.good()) return false;
        int32_t err = 0;
        is.read(reinterpret_cast<char*>(&err), sizeof(err));
        if (!is.good()) return false;
        p_oid = std::move(oid);
        p_valid = (validByte != 0);
        p_error = static_cast<AErrors>(err);
        return true;
    }
References p_error, and p_valid.
m_toStream()
virtual std::ostream & Alib::AObject::m_toStream (std::ostream & os) const inline protected virtual
{ return m_print(os); }
m_write()
virtual bool Alib::AObject::m_write (std::ostream & os) const inline nodiscard protected virtual
{
        os.write(reinterpret_cast<const char*>(&p_magic), sizeof(p_magic));
        os.write(reinterpret_cast<const char*>(&p_version), sizeof(p_version));
        uint32_t oidLen = static_cast<uint32_t>(p_oid.size());
        os.write(reinterpret_cast<const char*>(&oidLen), sizeof(oidLen));
        if (oidLen > 0) os.write(p_oid.data(), oidLen);
        uint8_t validByte = p_valid ? 1u : 0u;
        os.write(reinterpret_cast<const char*>(&validByte), sizeof(validByte));
        int32_t err = static_cast<int32_t>(p_error);
        os.write(reinterpret_cast<const char*>(&err), sizeof(err));
        return os.good();
    }
References p_error, and p_valid.
Oid()
const std::string & Alib::AObject::Oid () const inline nodiscard noexcept
{ return p_oid; }
operator!=()
bool Alib::AObject::operator!= (const AObject & other) const inline nodiscard noexcept
{ return !(*this == other); }
References operator==().
Referenced by operator=(), and operator=().
operator=() [1/2]
AObject & Alib::AObject::operator= (AObject && other) inline noexcept
{ if (*this != other) m_move(std::move(other)); return *this; }
References m_move(), and operator!=().
operator=() [2/2]
AObject & Alib::AObject::operator= (const AObject & other) inline
{ if (*this != other) m_copy(other); return *this; }
References m_copy(), and operator!=().
operator==()
bool Alib::AObject::operator== (const AObject & other) const inline nodiscard noexcept
{ return m_compare(other); }
References m_compare().
Referenced by operator!=().
printDescription()
virtual std::ostream & Alib::AObject::printDescription (std::ostream & os) const inline virtual
{ return m_printDescription(os); }
read()
virtual bool Alib::AObject::read (const std::string & fileName) inline nodiscard virtual
{
        std::ifstream is(fileName, std::ios::binary);
        if (!is.good()) return false;
        return m_read(is);
    }
resetError()
void Alib::AObject::resetError () inline noexcept
{ p_error = AErrors::noError; }
References Alib::noError, and p_error.
setError()
void Alib::AObject::setError (AErrors err) inline noexcept
{ p_error = err; }
References p_error.
setValid()
void Alib::AObject::setValid (bool valid) inline noexcept
{ p_valid = valid; }
References p_valid.
toStream()
virtual std::ostream & Alib::AObject::toStream (std::ostream & os) const inline virtual
{ return m_toStream(os); }
valid()
bool Alib::AObject::valid () const inline nodiscard noexcept
{ return p_valid; }
References p_valid.
validate()
void Alib::AObject::validate () inline noexcept
{ p_valid = true; }
References p_valid.
write()
virtual bool Alib::AObject::write (const std::string & fileName) const inline nodiscard virtual
{
        std::ofstream os(fileName, std::ios::binary);
        if (!os.good()) return false;
        return m_write(os);
    }
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & os, const AObject & obj) friend
{ return obj.toStream(os); }
operator>>
std::istream & operator>> (std::istream & is, AObject & obj) friend
{ return obj.fromStream(is); }
Member Data Documentation
p_error
AErrors Alib::AObject::p_error {AErrors::noError} protected
{AErrors::noError};
Referenced by errorName(), getError(), m_copy(), m_move(), m_parse(), m_read(), m_write(), resetError(), and setError().
p_magic
uint32_t Alib::AObject::p_magic {AOBJ_MAGIC} protected
{AOBJ_MAGIC};
p_oid
std::string Alib::AObject::p_oid protected
p_valid
bool Alib::AObject::p_valid {true} protected
{true};
Referenced by invalidate(), m_copy(), m_isValid(), m_move(), m_parse(), m_printStatus(), m_read(), m_write(), setValid(), valid(), and validate().
p_version
uint32_t Alib::AObject::p_version {AOBJ_VERSION} protected
{AOBJ_VERSION};
The documentation for this class was generated from the following file:
ALib/AObject.h