Alib: Alib::AShape Class Reference
Alib::AShape Class Reference
#include <AShape.h>
Public Member Functions
AShape ()=default
AShape (const std::vector< size_t > &dims)
size_t rank () const noexcept
const std::vector< size_t > & dims () const noexcept
const std::vector< size_t > & strides () const noexcept
void setDims (const std::vector< size_t > &dims)
void setStrides (const std::vector< size_t > &s)
size_t totalSize () const
size_t flatIndex (const std::vector< size_t > &idx) const
AShape sliceShape (const std::vector< size_t > &start, const std::vector< size_t > &stop, const std::vector< size_t > &step) const
size_t flatIndexFromSlice (size_t idx, const std::vector< size_t > &start, const std::vector< size_t > &step) const
void transpose (const std::vector< size_t > &axes)
bool operator== (const AShape &other) const
bool operator!= (const AShape &other) const
Static Public Member Functions
static AShape broadcast (const AShape &a, const AShape &b)
Private Member Functions
void calcStrides ()
Private Attributes
std::vector< size_t > p_dims
std::vector< size_t > p_strides
Detailed Description
Constructor & Destructor Documentation
AShape() [1/2]
Alib::AShape::AShape () default
AShape() [2/2]
Alib::AShape::AShape (const std::vector< size_t > & dims) inline explicit
: p_dims(dims) { calcStrides(); }
References calcStrides().
Member Function Documentation
broadcast()
AShape Alib::AShape::broadcast (const AShape & a, const AShape & b) inline static
{
        size_t r1=a.rank(), r2=b.rank();
        size_t rmax=std::max(r1,r2);
        std::vector<size_t> dims(rmax,1);
        for(size_t i=0;i<rmax;++i){
            size_t da=(i<rmax-r1?1:a.p_dims[i-(rmax-r1)]);
            size_t db=(i<rmax-r2?1:b.p_dims[i-(rmax-r2)]);
            if(da!=db && da!=1 && db!=1) throw std::invalid_argument("broadcast: incompatible shapes");
            dims[i]=std::max(da,db);
        }
        return AShape(dims);
    }
Referenced by Alib::AArray< T >::broadcastBinaryOp().
calcStrides()
void Alib::AShape::calcStrides () inline private
                      {
        p_strides.resize(rank());
        if(rank()==0) return;
        p_strides[rank()-1]=1;
        for(int i=int(rank())-2;i>=0;--i)
            p_strides[i] = p_strides[i+1]*p_dims[i+1];
    }
Referenced by AShape(), setDims(), and transpose().
dims()
const std::vector< size_t > & Alib::AShape::dims () const inline noexcept
{ return p_dims; }
flatIndex()
size_t Alib::AShape::flatIndex (const std::vector< size_t > & idx) const inline
{
        if(idx.size() != rank())
            throw std::runtime_error("AShape::flatIndex rank mismatch");
        size_t offset = 0;
        for(size_t i=0;i<p_dims.size();++i){
            if(idx[i] >= p_dims[i])
                throw std::out_of_range("AShape::flatIndex index out of bounds");
            offset += idx[i]*p_strides[i];
        }
        return offset;
    }
flatIndexFromSlice()
size_t Alib::AShape::flatIndexFromSlice (size_t idx, const std::vector< size_t > & start, const std::vector< size_t > & step) const inline
{
        size_t linear = 0;
        for(int d=int(rank())-1; d>=0; --d){
            size_t cur = idx % dims()[d];
            linear += (start[d] + cur*step[d])*strides()[d];
            idx /= dims()[d];
        }
        return linear;
    }
operator!=()
bool Alib::AShape::operator!= (const AShape & other) const inline
{ return !(*this==other); }
References operator==().
operator==()
bool Alib::AShape::operator== (const AShape & other) const inline
{ return p_dims==other.p_dims; }
Referenced by operator!=().
rank()
size_t Alib::AShape::rank () const inline noexcept
{ return p_dims.size(); }
setDims()
void Alib::AShape::setDims (const std::vector< size_t > & dims) inline
{ p_dims = dims; calcStrides(); }
References calcStrides().
setStrides()
void Alib::AShape::setStrides (const std::vector< size_t > & s) inline
{ p_strides = s; }
sliceShape()
AShape Alib::AShape::sliceShape (const std::vector< size_t > & start, const std::vector< size_t > & stop, const std::vector< size_t > & step) const inline
{
        if(start.size()!=rank() || stop.size()!=rank() || step.size()!=rank())
            throw std::invalid_argument("sliceShape: size mismatch");
        std::vector<size_t> newDims(rank());
        for(size_t i=0;i<rank();++i){
            if(step[i]==0) throw std::invalid_argument("sliceShape: step=0");
            newDims[i] = (stop[i]<=start[i]?0:(stop[i]-start[i]+step[i]-1)/step[i]);
        }
        return AShape(newDims);
    }
strides()
const std::vector< size_t > & Alib::AShape::strides () const inline noexcept
{ return p_strides; }
totalSize()
size_t Alib::AShape::totalSize () const inline
{
        return std::accumulate(p_dims.begin(), p_dims.end(), 1ULL, std::multiplies<size_t>());
    }
transpose()
void Alib::AShape::transpose (const std::vector< size_t > & axes) inline
{
        if(axes.size()!=rank()) throw std::invalid_argument("transpose: axes mismatch");
        std::vector<size_t> newDims(rank());
        for(size_t i=0;i<rank();++i) newDims[i]=p_dims[axes[i]];
        p_dims=newDims;
        calcStrides();
    }
References calcStrides().
Member Data Documentation
p_dims
std::vector<size_t> Alib::AShape::p_dims private
p_strides
std::vector<size_t> Alib::AShape::p_strides private
The documentation for this class was generated from the following file:
ALib/AShape.h