Alib: Alib::AArray< T > Class Template Reference
Alib::AArray< T > Class Template Reference
#include <AArray.h>
Public Types
using value_type = T
Public Member Functions
AArray ()=default
AArray (const std::vector< size_t > &dims)
AArray (const AShape &shape)
template<typename... Dims, typename = std::enable_if_t<(std::conjunction_v<std::is_integral<Dims>...>)>>
AArray (Dims... dims)
AArray (const std::initializer_list< size_t > &dims)
AArray (const AArray &other)
AArray (AArray &&other) noexcept
AArray & operator= (const AArray &other)
AArray & operator= (AArray &&other) noexcept
std::unique_ptr< AObject > clone () const override
size_t hash () const override
const AShape & shape () const noexcept
AArrayProxy< T > operator[] (size_t i)
const AArrayProxy< T > operator[] (size_t i) const
T & at (const std::vector< size_t > &idx)
const T & at (const std::vector< size_t > &idx) const
template<typename... Idx>
T & operator() (Idx... idx)
template<typename... Idx>
const T & operator() (Idx... idx) const
AArray< T > slice (const std::vector< size_t > &start, const std::vector< size_t > &stop, const std::vector< size_t > &step={}) const
void reshape (const std::vector< size_t > &newDims)
AArray< T > transpose (const std::vector< size_t > &axes={}) const
template<typename Op>
void inplaceBinaryOp (const AArray< T > &rhs, Op op)
AArray< T > & operator+= (const AArray< T > &rhs)
AArray< T > & operator-= (const AArray< T > &rhs)
AArray< T > & operator*= (const AArray< T > &rhs)
AArray< T > & operator/= (const AArray< T > &rhs)
std::shared_ptr< std::vector< T > > & dataPtr () noexcept
const std::shared_ptr< std::vector< T > > & dataPtr () const noexcept
size_t size () const noexcept
Public Member Functions inherited from Alib::AObject
AObject () noexcept
virtual ~AObject ()=default
AObject (const AObject &other)
AObject (AObject &&other) noexcept
AObject & operator= (const AObject &other)
AObject & operator= (AObject &&other) noexcept
const std::string & Oid () const noexcept
virtual std::string getClassName () const
bool valid () const noexcept
void setValid (bool valid) noexcept
void validate () noexcept
void invalidate () noexcept
AErrors getError () const noexcept
const char * errorName () const noexcept
void setError (AErrors err) noexcept
void resetError () noexcept
bool operator== (const AObject &other) const noexcept
bool operator!= (const AObject &other) const noexcept
virtual std::ostream & toStream (std::ostream &os) const
virtual std::istream & fromStream (std::istream &is)
virtual bool write (const std::string &fileName) const
virtual bool read (const std::string &fileName)
virtual std::ostream & printDescription (std::ostream &os) const
Protected Member Functions
void m_copy (const AArray &other)
void m_move (AArray &&other)
Protected Member Functions inherited from Alib::AObject
virtual void m_copy (const AObject &other)
virtual void m_move (AObject &&other) noexcept
virtual bool m_compare (const AObject &other) const noexcept
virtual bool m_isValid () const noexcept
virtual std::ostream & m_printDescription (std::ostream &os) const
virtual std::ostream & m_printStatus (std::ostream &os) const
virtual std::ostream & m_print (std::ostream &os) const
virtual std::istream & m_parse (std::istream &is)
virtual bool m_write (std::ostream &os) const
virtual bool m_read (std::istream &is)
virtual std::ostream & m_toStream (std::ostream &os) const
virtual std::istream & m_fromStream (std::istream &is)
Static Protected Member Functions
template<typename Op>
static AArray< T > broadcastBinaryOp (const AArray< T > &lhs, const AArray< T > &rhs, Op op)
Static Protected Member Functions inherited from Alib::AObject
static std::string generateOID ()
Protected Attributes
AShape p_shape
std::shared_ptr< std::vector< T > > p_dataPtr
Protected Attributes inherited from Alib::AObject
uint32_t p_magic {AOBJ_MAGIC}
uint32_t p_version {AOBJ_VERSION}
std::string p_oid
bool p_valid {true}
AErrors p_error {AErrors::noError}
Friends
AArray< T > operator+ (const AArray< T > &lhs, const AArray< T > &rhs)
AArray< T > operator- (const AArray< T > &lhs, const AArray< T > &rhs)
AArray< T > operator* (const AArray< T > &lhs, const AArray< T > &rhs)
AArray< T > operator/ (const AArray< T > &lhs, const AArray< T > &rhs)
Detailed Description
template<typename T>
class Alib::AArray< T >
Member Typedef Documentation
value_type
template<typename T> using Alib::AArray< T >::value_type = T
Constructor & Destructor Documentation
AArray() [1/7]
template<typename T> Alib::AArray< T >::AArray () default
AArray() [2/7]
template<typename T> Alib::AArray< T >::AArray (const std::vector< size_t > & dims) inline explicit
        : p_shape(dims), p_dataPtr(std::make_shared<std::vector<T>>(p_shape.totalSize())) {}
References AArray().
Referenced by AArray(), and AArray().
AArray() [3/7]
template<typename T> Alib::AArray< T >::AArray (const AShape & shape) inline explicit
        : p_shape(shape), p_dataPtr(std::make_shared<std::vector<T>>(p_shape.totalSize())) {}
References AArray().
Referenced by AArray().
AArray() [4/7]
template<typename T> template<typename... Dims, typename = std::enable_if_t<(std::conjunction_v<std::is_integral<Dims>...>)>> Alib::AArray< T >::AArray (Dims... dims) inline explicit
        : p_shape(std::vector<size_t>{static_cast<size_t>(dims)...}),
          p_dataPtr(std::make_shared<std::vector<T>>(p_shape.totalSize())) {}
References AArray().
Referenced by AArray().
AArray() [5/7]
template<typename T> Alib::AArray< T >::AArray (const std::initializer_list< size_t > & dims) inline explicit
        : p_shape(dims), p_dataPtr(std::make_shared<std::vector<T>>(p_shape.totalSize())) {}
References AArray().
AArray() [6/7]
template<typename T> Alib::AArray< T >::AArray (const AArray< T > & other) inline
{ m_copy(other); }
References m_copy().
AArray() [7/7]
template<typename T> Alib::AArray< T >::AArray (AArray< T > && other) inline noexcept
{ m_move(std::move(other)); }
References m_move().
Member Function Documentation
at() [1/2]
template<typename T> T & Alib::AArray< T >::at (const std::vector< size_t > & idx) inline
{
        if(idx.size()!=p_shape.rank()) throw std::invalid_argument("at: rank mismatch");
        return p_dataPtr->at(p_shape.flatIndex(idx));
    }
at() [2/2]
template<typename T> const T & Alib::AArray< T >::at (const std::vector< size_t > & idx) const inline
{
        if(idx.size()!=p_shape.rank()) throw std::invalid_argument("at: rank mismatch");
        return p_dataPtr->at(p_shape.flatIndex(idx));
    }
broadcastBinaryOp()
template<typename T> template<typename Op> AArray< T > Alib::AArray< T >::broadcastBinaryOp (const AArray< T > & lhs, const AArray< T > & rhs, Op op) inline static protected
{
        AShape resultShape = AShape::broadcast(lhs.shape(),rhs.shape());
        AArray<T> result(resultShape);
        const auto& lhsDims=lhs.shape().dims();
        const auto& rhsDims=rhs.shape().dims();
        const auto& lhsStrides=lhs.shape().strides();
        const auto& rhsStrides=rhs.shape().strides();
        const auto& resDims=resultShape.dims();
        auto& resData = result.p_dataPtr;
        const auto& lhsData = lhs.p_dataPtr;
        const auto& rhsData = rhs.p_dataPtr;
        size_t rankRes = resultShape.rank();
        size_t rankL = lhs.shape().rank();
        size_t rankR = rhs.shape().rank();
        for(size_t i=0;i<resultShape.totalSize();++i){
            size_t idx=i;
            size_t lhsIdx=0, rhsIdx=0;
            for(int d=int(rankRes)-1;d>=0;--d){
                size_t cur = idx % resDims[d];
                size_t ldim = (d>=rankRes-rankL)?lhsDims[d-(rankRes-rankL)]:1;
                size_t rdim = (d>=rankRes-rankR)?rhsDims[d-(rankRes-rankR)]:1;
                size_t lstride=(d>=rankRes-rankL)?lhsStrides[d-(rankRes-rankL)]:0;
                size_t rstride=(d>=rankRes-rankR)?rhsStrides[d-(rankRes-rankR)]:0;
                lhsIdx += (ldim==1?0:cur*lstride);
                rhsIdx += (rdim==1?0:cur*rstride);
                idx/=resDims[d];
            }
            (*resData)[i] = op((*lhsData)[lhsIdx], (*rhsData)[rhsIdx]);
        }
        return result;
    }
References Alib::AShape::broadcast(), and shape().
clone()
template<typename T> std::unique_ptr< AObject > Alib::AArray< T >::clone () const inline override virtual
Implements Alib::AObject.
{ return std::make_unique<AArray<T>>(*this); }
dataPtr() [1/2]
template<typename T> const std::shared_ptr< std::vector< T > > & Alib::AArray< T >::dataPtr () const inline noexcept
{ return p_dataPtr; }
dataPtr() [2/2]
template<typename T> std::shared_ptr< std::vector< T > > & Alib::AArray< T >::dataPtr () inline noexcept
{ return p_dataPtr; }
hash()
template<typename T> size_t Alib::AArray< T >::hash () const inline override virtual
Reimplemented from Alib::AObject.
{
        size_t h=0;
        for(const auto& v:*p_dataPtr) h ^= std::hash<T>{}(v)+0x9e3779b9+(h<<6)+(h>>2);
        return h;
    }
inplaceBinaryOp()
template<typename T> template<typename Op> void Alib::AArray< T >::inplaceBinaryOp (const AArray< T > & rhs, Op op) inline
{
        auto result = broadcastBinaryOp(*this,rhs,op);
        *this = std::move(result);
    }
m_copy()
template<typename T> void Alib::AArray< T >::m_copy (const AArray< T > & other) inline protected
{
        AObject::m_copy(other);
        p_shape=other.p_shape;
        p_dataPtr=std::make_shared<std::vector<T>>(*other.p_dataPtr);
    }
References Alib::AObject::m_copy().
Referenced by AArray(), and operator=().
m_move()
template<typename T> void Alib::AArray< T >::m_move (AArray< T > && other) inline protected
{
        AObject::m_move(std::move(other));
        p_shape=std::move(other.p_shape);
        p_dataPtr=std::move(other.p_dataPtr);
    }
References Alib::AObject::m_move().
Referenced by AArray(), and operator=().
operator()() [1/2]
template<typename T> template<typename... Idx> T & Alib::AArray< T >::operator() (Idx... idx) inline
{
        return at(std::vector<size_t>{static_cast<size_t>(idx)...});
    }
operator()() [2/2]
template<typename T> template<typename... Idx> const T & Alib::AArray< T >::operator() (Idx... idx) const inline
{
        return at(std::vector<size_t>{static_cast<size_t>(idx)...});
    }
operator*=()
template<typename T> AArray< T > & Alib::AArray< T >::operator*= (const AArray< T > & rhs) inline
{ inplaceBinaryOp(rhs,[](T x,T y){return x*y;}); return *this;}
operator+=()
template<typename T> AArray< T > & Alib::AArray< T >::operator+= (const AArray< T > & rhs) inline
{ inplaceBinaryOp(rhs,[](T x,T y){return x+y;}); return *this;}
operator-=()
template<typename T> AArray< T > & Alib::AArray< T >::operator-= (const AArray< T > & rhs) inline
{ inplaceBinaryOp(rhs,[](T x,T y){return x-y;}); return *this;}
operator/=()
template<typename T> AArray< T > & Alib::AArray< T >::operator/= (const AArray< T > & rhs) inline
{ inplaceBinaryOp(rhs,[](T x,T y){return x/y;}); return *this;}
operator=() [1/2]
template<typename T> AArray & Alib::AArray< T >::operator= (AArray< T > && other) inline noexcept
{ if(this!=&other) m_move(std::move(other)); return *this; }
References m_move().
operator=() [2/2]
template<typename T> AArray & Alib::AArray< T >::operator= (const AArray< T > & other) inline
{ if(this!=&other) m_copy(other); return *this; }
References m_copy().
operator[]() [1/2]
template<typename T> AArrayProxy< T > Alib::AArray< T >::operator[] (size_t i) inline
{ return AArrayProxy<T>(this,{i}); }
operator[]() [2/2]
template<typename T> const AArrayProxy< T > Alib::AArray< T >::operator[] (size_t i) const inline
{ return AArrayProxy<T>(const_cast<AArray<T>*>(this),{i}); }
reshape()
template<typename T> void Alib::AArray< T >::reshape (const std::vector< size_t > & newDims) inline
{
        size_t newTotal=std::accumulate(newDims.begin(),newDims.end(),1ULL,std::multiplies<size_t>());
        if(newTotal != size()) throw std::invalid_argument("reshape: total mismatch");
        p_shape.setDims(newDims);
    }
shape()
template<typename T> const AShape & Alib::AArray< T >::shape () const inline noexcept
{ return p_shape; }
Referenced by broadcastBinaryOp().
size()
template<typename T> size_t Alib::AArray< T >::size () const inline noexcept
{ return p_dataPtr->size(); }
slice()
template<typename T> AArray< T > Alib::AArray< T >::slice (const std::vector< size_t > & start, const std::vector< size_t > & stop, const std::vector< size_t > & step = {}) const inline
{
        std::vector<size_t> sstep = step.empty()? std::vector<size_t>(p_shape.rank(),1):step;
        AShape newShape = p_shape.sliceShape(start,stop,sstep);
        AArray<T> result(newShape);
        for(size_t i=0;i<result.size();++i){
            size_t srcIdx=p_shape.flatIndexFromSlice(i,start,sstep);
            (*result.p_dataPtr)[i]=(*p_dataPtr)[srcIdx];
        }
        return result;
    }
transpose()
template<typename T> AArray< T > Alib::AArray< T >::transpose (const std::vector< size_t > & axes = {}) const inline
{
        AShape tshape = p_shape;
        if(axes.empty()){
            std::vector<size_t> perm(p_shape.rank());
            for(size_t i=0;i<p_shape.rank();++i) perm[i]=p_shape.rank()-1-i;
            tshape.transpose(perm);
        } else tshape.transpose(axes);
        AArray<T> result;
        result.p_shape = tshape;
        result.p_dataPtr = p_dataPtr; // shared view
        return result;
    }
Friends And Related Symbol Documentation
operator*
template<typename T> AArray< T > operator* (const AArray< T > & lhs, const AArray< T > & rhs) friend
{ return broadcastBinaryOp(lhs,rhs,std::multiplies<T>()); }
operator+
template<typename T> AArray< T > operator+ (const AArray< T > & lhs, const AArray< T > & rhs) friend
{ return broadcastBinaryOp(lhs,rhs,std::plus<T>()); }
operator-
template<typename T> AArray< T > operator- (const AArray< T > & lhs, const AArray< T > & rhs) friend
{ return broadcastBinaryOp(lhs,rhs,std::minus<T>()); }
operator/
template<typename T> AArray< T > operator/ (const AArray< T > & lhs, const AArray< T > & rhs) friend
{ return broadcastBinaryOp(lhs,rhs,std::divides<T>()); }
Member Data Documentation
p_dataPtr
template<typename T> std::shared_ptr<std::vector<T> > Alib::AArray< T >::p_dataPtr protected
p_shape
template<typename T> AShape Alib::AArray< T >::p_shape protected
The documentation for this class was generated from the following file:
ALib/AArray.h